# Generated by Django 5.0.6 on 2024-07-08 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_artist_is_artist_profile_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='is_artist',
        ),
    ]
