# Generated by Django 5.0.6 on 2024-07-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_artist_is_artist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_artist',
        ),
        migrations.DeleteModel(
            name='Artist',
        ),
    ]
