# Generated by Django 5.0.6 on 2024-07-11 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='.../default_profile_relxos.jpg', upload_to='images/'),
        ),
    ]
