# Generated by Django 5.0.6 on 2024-07-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_rename_artist_review_post_review_tags_review_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='content',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
